### PR TITLE
created page under construction

### PR DESCRIPTION
**Pull request by Wind1013**
Comments and suggestions are always welcome :)

### CODE REVIEW

**Comment by letthefireflieslive** [comment]
Nice! One request, let' change the background color to white or none.. text color to green and yellow for branding

**Comment by Wind1013** [comment]
Copy that!

**Comment by letthefireflieslive** [comment]
Good for now. Next time when the codebase gets bigger we need to keep styling in css files :)

**Comment by Wind1013** [comment]
Will keep that in mind! Thanks :)

**Pull request merged**
